### ISSUE TITLE
Windows Wallet freezes during sync

### ISSUE THREAD

**Issue by alec-djinn** [pepeteam/pepecoin#25]
I followed the instruction to using snapshot bootstrap + Link to bootstrap to sync your Pepecoin-qt 
https://t.co/BsVOW1dLJY but I can't get it to work. It freezes continuously.
I am using Windows 10 running on VirtualBox. Any clue?

![untitled](https://user-images.githubusercontent.com/6241875/34579481-170f4db2-f181-11e7-8ce7-562c4fdcfdc1.png)

**Comment by damoos3** [comment]
Use this version of the snapshot 

http://seed2.freepepe.org/memetic-pepecoin-chainsync-1-1-18.zip

its the newest snapshot, also try adding some nodes. If still stuck join the tg t.me/pepecoins sure someone there can help you out.  


> addnode=162.248.93.192
addnode=seed1.freepepe.org
addnode=seed2.freepepe.org
addnode=seed3.freepepe.org
addnode=seed4.freepepe.org
addnode=45.32.129.79
addnode=45.63.86.183
addnode=45.76.93.158
addnode=45.76.25.154
addnode=45.79.175.159
addnode=45.79.156.12
addnode=45.56.84.240
addnode=207.246.124.170
addnode=104.238.167.134
addnode=45.32.67.176

**Comment by alec-djinn** [comment]
Thanks, that solved the problem. I can now finish the synchronisation. However, I still experience freezes every now and then.
