### ISSUE TITLE
Error: could not allocate vin for collateral Address

### ISSUE THREAD

**Issue by alec-djinn** [pepeteam/pepecoin#27]
I get this when I try to start a Local Mastertoad. Why? How to solve it?
I followed the instructions:

```
...
7.   You   will   see   a   notification   for   a   'Darksend   Make   Collateral   Inputs'
8.   Wait   for   the   collateral   transaction   to   reach   20   confirmations   (you   can   see   this   on   the Transactions   tab   in   the   wallet)
9.   Restart   the   wallet
10.  Go   to   the   'Mastertoads'   tab   in   the   sidebar,   and   then   to   the   'My   Mastertoads'   tab.
12.  Highlight   your   new   Mastertoad   configuration   under   the   Alias   'Local   Mastertoad'   and   select   it.
13.  Click   Start.   Your   Mastertoad   will   now   start   and   be   listed   in   the   'PepeCoin   Network'   tab
```

But I get that error after I click Start.

**Comment by damoos3** [comment]
Unlock wallet and uncheck for staking only

**Comment by alec-djinn** [comment]
It's working now. Thanks. I would add it to the guide though.

**Comment by alec-djinn** [comment]
I have spoken too early. It worked at first. The I have restarted it, unlocked it and it's returning the same error again...

**Comment by damoos3** [comment]
If you sent the collateral correctly, and have unchecked for staking only when unlocking it should not give this error

**Comment by damoos3** [comment]
Also check if the vps its connecting to is upto date and synced

**Comment by alec-djinn** [comment]
It's a local one.

**Comment by damoos3** [comment]
You could always just remake the config, remove old and hit Create Local and wait 10 confirmations and click run. Doesnt take to long

**Comment by alec-djinn** [comment]
Shall I remove the current "Local Mastertoad" and make a new one?

**Comment by damoos3** [comment]
Yes remake its easy, mayne the collateral wasnt sent properly first time n the just repeat what i said above

**Comment by alec-djinn** [comment]
Yep, it worked. Still puzzled about what happened before...
