### ISSUE TITLE
versions 2.7+ crashing on windows

### ISSUE THREAD

**Issue by 2ge** [pepeteam/pepecoin#31]
Hi

Windows 7; try to download any version higher than 2.7.0.0 and I tried it until 2.8.1.0 version, delete data dir and run wallet. It is crashing.

**Comment by damoos3** [comment]
hop on telegram t.me/pepecoins you can get support there try using snapshot on http://seed2.pepecoin.co/memetic-pepecoin-chainsync-11-16-2018.tar

you need to run version 2.8.1.0

**Comment by 2ge** [comment]
ok, I came there. The question is, did you tried to run vanilla 2.8.1.0 on windows (no dump/chainsync)? it is crashing without it...

**Comment by projectmemetic** [comment]
We're aware of the issue and looking into it :-)  Thanks for reporting here...  Will advise when it is fixed.

**Comment by cyberpepe** [comment]
Version 2.8.1.0 resolves this issue. You may need to create c:\Users\yourname\Appdata\Pepecoin if you have any other issues.

**Comment by projectmemetic** [comment]
see pull request
